
#define HAL_BARO_ALLOW_INIT_NO_BARO
#define EMBOX_INS_STUB

#undef AP_RCPROTOCOL_ENABLED
#define AP_RCPROTOCOL_ENABLED 1

#undef AP_RCPROTOCOL_BACKEND_DEFAULT_ENABLED
#define AP_RCPROTOCOL_BACKEND_DEFAULT_ENABLED 0

#undef AP_RCPROTOCOL_UDP_ENABLED
#define AP_RCPROTOCOL_UDP_ENABLED 1

// #undef AP_RCPROTOCOL_CRSF_ENABLED
// #define AP_RCPROTOCOL_CRSF_ENABLED 1

// #undef HAL_CRSF_TELEM_ENABLED
// #define HAL_CRSF_TELEM_ENABLED 1
