#define AP_BARO_ENABLED 1
#define AP_BARO_BMP280_ENABLED 1
#define AP_BARO_PROBE_EXT_PARAMETER_ENABLED 1
#define HAL_BARO_PROBE_EXT_DEFAULT 7

#define HAL_INS_PROBE_LIST PROBE_IMU_SPI(Invensense, "mpu6000", ROTATION_YAW_90);
