TARGET = embox

ARCH = arm

CHIP_VENDOR = stm32
PLATFORM_VENDOR = stm32
PLATFORM = nucleo_f767zi

CROSS_COMPILE = arm-none-eabi-


//CPPFLAGS += -DNDEBUG

CFLAGS += -O0 -g
CFLAGS += -mthumb -mlittle-endian
CFLAGS += -ffreestanding
CFLAGS += -mcpu=cortex-m7
CFLAGS += -mfpu=fpv5-sp-d16 -mfloat-abi=hard


CXXFLAGS += -O0 -g
CXXFLAGS += -mthumb -mlittle-endian
CXXFLAGS += -mcpu=cortex-m7
CXXFLAGS += -fno-threadsafe-statics
CXXFLAGS += -mfpu=fpv5-sp-d16 -mfloat-abi=hard
