#pragma once

#define HAL_BOARD_NAME "EMBOX"
#define HAL_CPU_CLASS HAL_CPU_CLASS_150
#define HAL_MEM_CLASS HAL_MEM_CLASS_192
#ifndef HAL_STORAGE_SIZE
#define HAL_STORAGE_SIZE 16384
#endif
#define HAL_STORAGE_SIZE_AVAILABLE HAL_STORAGE_SIZE
#define HAL_INS_DEFAULT HAL_INS_NONE
#define HAL_BARO_DEFAULT HAL_BARO_NONE

#define HAL_HAVE_BOARD_VOLTAGE 0
#define HAL_HAVE_SERVO_VOLTAGE 0
#define HAL_HAVE_SAFETY_SWITCH 0
#define HAL_WITH_MCU_MONITORING 0
#define HAL_USE_QUADSPI 0
#define HAL_WITH_DSP 0

#define HAL_CANFD_SUPPORTED 0
#define HAL_NUM_CAN_IFACES 0

#define HAL_BOARD_LOG_DIRECTORY "logs"
#define HAL_BOARD_TERRAIN_DIRECTORY "terrain"
#define HAL_BOARD_STORAGE_DIRECTORY "."

#ifdef __cplusplus
#include <AP_HAL_Embox/Semaphores.h>
#define HAL_Semaphore Embox::Semaphore
#define HAL_BinarySemaphore Embox::BinarySemaphore
#endif

#define HAL_LOGGING_FILESYSTEM_ENABLED 0
#define AP_FILESYSTEM_POSIX_HAVE_FSYNC 0
#define AP_FILESYSTEM_POSIX_HAVE_STATFS 0

#define AP_AIRSPEED_MS4525_ENABLED 0
#define AP_AIRSPEED_ENABLED 0
#define AP_AIRSPEED_ANALOG_ENABLED 0
#define AP_AIRSPEED_BACKEND_DEFAULT_ENABLED 0

#define AP_COMPASS_ENABLE_DEFAULT 0
#define ALLOW_ARM_NO_COMPASS

#define AP_MOTORS_FRAME_DEFAULT_ENABLED 0
#define AP_MOTORS_FRAME_QUAD_ENABLED 1

#define HAL_NAVEKF2_AVAILABLE 0
#define EK3_FEATURE_BODY_ODOM 0
#define EK3_FEATURE_EXTERNAL_NAV 0
#define EK3_FEATURE_DRAG_FUSION 0
#define HAL_ADSB_ENABLED 0
#define HAL_PROXIMITY_ENABLED 0
#define HAL_VISUALODOM_ENABLED 0
#define HAL_GENERATOR_ENABLED 0
#define HAL_MOUNT_ENABLED 0
#define HAL_EFI_ENABLED 0
#define HAL_LOGGING_ENABLED 0
#define HAL_CRSF_TELEM_ENABLED 0
#define MODE_AUTOROTATE_ENABLED 0
#define AP_EXTERNAL_CONTROL_ENABLED 0
#define AP_BEACON_ENABLED 0
#define AP_AVOIDANCE_ENABLED 0
#define AC_PRECLAND_ENABLED 0
#define AP_CAMERA_ENABLED 0
#define AP_RPM_ENABLED 0
#define AP_RANGEFINDER_ENABLED 0
#define OSD_ENABLED 0
#define OSD_PARAM_ENABLED 0
#define HAL_WITH_MSP_DISPLAYPORT 0
#define AP_LANDINGGEAR_ENABLED 0
#define HAL_MSP_OPTICALFLOW_ENABLED 0
#define HAL_SUPPORT_RCOUT_SERIAL 0
#define HAL_HOTT_TELEM_ENABLED 0
#define HAL_GYROFFT_ENABLED 0
#define AP_SIM_INS_FILE_ENABLED 0
#define AP_AIRSPEED_AUTOCAL_ENABLE 0
#define AP_CAN_SLCAN_ENABLED 0
#define AP_ICENGINE_ENABLED 0
// #define AP_MISSION_ENABLED 0
#define AP_RCPROTOCOL_ENABLED 0
#define AP_RTC_ENABLED 0
// #define AP_SCHEDULER_ENABLED 0
#define AP_SCRIPTING_ENABLED 0
#define AP_STATS_ENABLED 0
#define AP_FENCE_ENABLED 0
#define HAL_SPRAYER_ENABLED 0
#define HAL_INS_ACCELCAL_ENABLED 0
#define AP_ADVANCEDFAILSAFE_ENABLED 0
// #define AP_AHRS_ENABLED 0
#define AP_AHRS_DCM_ENABLED 0
// #define AP_AHRS_EXTERNAL_ENABLED 0
// #define HAL_EXTERNAL_AHRS_ENABLED 0
#define AP_FOLLOW_ENABLED 0

#define AP_BARO_BMP280_ENABLED 0
#define AP_BARO_PROBE_EXT_PARAMETER_ENABLED 0

// Uncomment this to use BMP280 baro
// #define AP_BARO_ENABLED 1
// #define AP_BARO_BMP280_ENABLED 1
// #define AP_BARO_PROBE_EXT_PARAMETER_ENABLED 1
// #define HAL_BARO_PROBE_EXT_DEFAULT 7

#define AP_BARO_SPL06_ENABLED 0
#define AP_BARO_SPL06_BACKGROUND_ENABLE 0
#define AP_BARO_MSP_ENABLED 0
#define AP_BARO_FBM320_ENABLED 0
#define AP_BARO_1976_STANDARD_ATMOSPHERE_ENABLED 0
#define AP_BARO_ICM20789_ENABLED 0
// #define AP_BARO_DRONECAN_ENABLED 0
#define AP_BARO_MS56XX_ENABLED 0
#define AP_BARO_BMP388_ENABLED 0
#define AP_BARO_BMP581_ENABLED 0
#define AP_BARO_EXTERNALAHRS_ENABLED 0
#define AP_BARO_ICP201XX_ENABLED 0
// #define AP_BARO_DUMMY_ENABLED 0
#define AP_BARO_KELLERLD_ENABLED 0

#define AP_BARO_DPS280_ENABLED 0
#define AP_BARO_LPS2XH_ENABLED 0
#define AP_BARO_BMP085_ENABLED 0
// #define AP_BATTERY_ENABLED 0
// #define AP_BATTERY_TORQEEDO_ENABLED 0
#define AP_BATTERY_AD7091R5_ENABLED 0
#define AP_BATTERY_FUELLEVEL_ANALOG_ENABLED 0
#define AP_BATTERY_SMBUS_SUI_ENABLED 0
#define AP_BATTERY_SMBUS_ROTOYE_ENABLED 0
#define AP_BATTERY_SUM_ENABLED 0
#define AP_BATTERY_INA2XX_ENABLED 0
#define AP_BATTERY_ANALOG_ENABLED 0
#define AP_BATTERY_FUELFLOW_ENABLED 0
#define AP_BATTERY_SMBUS_ENABLED 0
#define AP_BATTERY_SMBUS_GENERIC_ENABLED 0
#define AP_BATTERY_SYNTHETIC_CURRENT_ENABLED 0
#define AP_BATTERY_FUELLEVEL_PWM_ENABLED 0

// #define COMPASS_MOT_ENABLED 0
#define AP_COMPASS_DIAGONALS_ENABLED 0

// #define AP_COMPASS_ENABLED 0
// #define AP_COMPASS_AK8963_ENABLED 0
// #define AP_COMPASS_AK09916_ENABLED 0
// #define AP_COMPASS_BMM150_ENABLED 0
// #define AP_COMPASS_BMM350_ENABLED 0
#define COMPASS_CAL_ENABLED 0
// #define AP_COMPASS_DRONECAN_ENABLED 0
// #define AP_COMPASS_EXTERNALAHRS_ENABLED 0
// #define AP_COMPASS_HMC5843_ENABLED 0
// #define AP_COMPASS_IIS2MDC_ENABLED 0
// #define AP_COMPASS_IST8308_ENABLED 0
// #define AP_COMPASS_IST8310_ENABLED 0
// #define AP_COMPASS_LIS3MDL_ENABLED 0
// #define AP_COMPASS_LSM9DS1_ENABLED 0
// #define AP_COMPASS_LSM303D_ENABLED 0
// #define AP_COMPASS_MAG3110_ENABLED 0
// #define AP_COMPASS_MMC5XX3_ENABLED 0
// #define AP_COMPASS_MMC3416_ENABLED 0
// #define AP_COMPASS_MSP_ENABLED 0
// #define AP_COMPASS_QMC5883L_ENABLED 0
// #define AP_COMPASS_QMC5883P_ENABLED 0
// #define AP_COMPASS_RM3100_ENABLED 0
// #define AP_COMPASS_SITL_ENABLED 0
#define COMPASS_LEARN_ENABLED 0

#define HAL_CAN_DEFAULT_NODE_ID 0
#define HAL_CANMANAGER_ENABLED 0
// #define HAL_GCS_ENABLED 0
#define HAL_LOGGING_MAVLINK_ENABLED 0
#define HAL_RALLY_ENABLED 0
#define AP_TERRAIN_AVAILABLE 0
#define AP_CUSTOMROTATIONS_ENABLED 0

#define AP_GRIPPER_ENABLED 0
#define AP_GRIPPER_EPM_ENABLED 0
#define AP_GRIPPER_SERVO_ENABLED 0

// #define AP_SMARTAUDIO_ENABLED 0
// #define AP_RELAY_ENABLED 0
// #define AP_VIDEOTX_ENABLED 0
// #define HAL_RUNCAM_ENABLED 0
// #define HAL_HAVE_AP_ROMFS_EMBEDDED_H 0
// #define AP_ROMFS 0

// #define AP_CUSTOMCONTROL_ENABLED 0
